package com.example.wardrobe.config

val DEBUG_ON = false
val SHIRT_FRAGMENT = 100
val REQUEST_CODE_CAPTURE_SHIRT_IMAGE_PERMISSION = 101
val REQUEST_SHIRT_IMAGE_CAPTURE = 102

val TROUSER_FRAGMENT = 200
val REQUEST_CODE_CAPTURE_TROUSER_IMAGE_PERMISSION = 201
val REQUEST_TROUSER_IMAGE_CAPTURE = 202
